config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/generate_report'
  root 'front_view#index'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'admin/admin_menu'

  resources :employees

  resources :stores

  resources :reports

  resources :front_view

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assitance.rb
class Assitance < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :front_views, foreign_key:"employee_id"
end

app/models/front_view.rb
class FrontView < ApplicationRecord
  belongs_to :employee, foreign_key:"employee_id"
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


        u = User.new(:email => "admin@example.com", :password => 'password', :password_confirmation => 'password')
        u.save
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def admin_menu
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def after_sign_in_path_for(resource)
        admin_admin_menu_path
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    employee = Employee.find(params[:id])
    employee.update(employee_params)
    
    redirect_to employees_path
  end

  def create
    employee = Employee.new(employee_params)
    employee.save
    redirect_to employees_path
  end

  def destroy
    employee = Employee.find(params[:id])
    employee.destroy
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:email, :name, :position, :employee_num, :employee_private_num)
  end
end

app/controllers/front_view_controller.rb
class FrontViewController < ApplicationController
  def index
    nil
  end

  def create
    @employee = Employee.find_by(employee_params)
    unless @employee.nil?
      @check = @employee.front_views.new(check_params)
      @check.save ? flash[:notice] = 'Successfully check' : flash[:alert] = 'Checking faill'
    else
      flash[:alert] = 'Wrong number or password'
    end
    
    redirect_back(fallback_location: root_path)

  end

  private

  def employee_params
    params.permit(:employee_num, :employee_private_num)
  end

  def check_params
    params.permit(:check)

  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @front_views = FrontView.all
    @employees = Employee.all
  end

  def generate_report
    @front_views = FrontView.all
    @employees = Employee.all

  end

  def show
    @front_views = FrontView.find(params[:id])
    @employees = Employee.find(paramns[:id])
  end

  private

  def employee_params
    params.require(:employee).permit(:email, :name, :position, :employee_num, :employee_private_num)
  end

  def checks_params
    params.require(:front_view).permit(:check, :employee_id, :created_at, :updated_at)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    store = Store.find(params[:id])
    store.update(store_params)
    
    redirect_to stores_path
  end

  def create
    store = Store.new(store_params)
    store.save

    redirect_to stores_path
  end

  def destroy
    store = Store.find(params[:id])
    store.destroy
    redirect_to stores_path
  end
  
  private

  def store_params
    params.require(:store).permit(:name, :address)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/front_view_helper.rb
module FrontViewHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/admin/admin_menu.html.erb
<div id="title" class="mt-3"> <h1>Admin Menu</h1> </div>

<div class="d-md-flex justify-content-between align-items-center mx-5 mx-md-10 mt-5 px-5">
    <div id="menu" class="col-md-3 p-5">
        <%= link_to image_tag("empleados.png", alt: "employee image", class: 'img-fluid'), employees_path %>
        <p class="row justify-content-center h1 p-3">Employees</p>
    </div>
    <div class="col-md-3 p-5">
        <%= link_to image_tag("tienda.png", alt: "store image", class: 'img-fluid'), stores_path %>
        <p class="row justify-content-center h1 p-3">Stores</p>
    </div>
    <div class="col-md-3 p-5">
        <%= link_to image_tag("reporte.png", alt: "report image", class: 'img-fluid'), reports_path %>
        <p class="row justify-content-center h1 p-3">Reports</p>
    </div>
</div>

app/views/employees/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Edit employee</h4>
  </div>
  <div class="row justify-content-center">
    <%= form_with(model: @employee, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_area :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :position %>
        <%= form.text_area :position, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :employee_num %>
        <%= form.text_area :employee_num, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :employee_private_num %>
        <%= form.text_area :employee_private_num, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 display-4">Employees</h4>
  </div>
  <%= link_to 'Register employee', new_employee_path %>
  <% if @employees.present? %>
    <div class="row justify-content-center">
      <table class="table table-bordered table-dark">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">Name</th>
            <th scope="col">Position</th>
            <th scope="col">Employee Number</th>
            <th scope="col">Employee Private Number</th>
            <th scope="col" colspan="3">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.email %></td>
              <td><%= employee.name %></td>
              <td><%= employee.position %></td>
              <td><%= employee.employee_num %></td>
              <td><%= employee.employee_private_num %></td>

              <td><%= link_to 'Show', employee_path(employee.id) %></td>
              <td><%= link_to 'Edit', edit_employee_path(employee.id) %></td>
              <td><%= button_to 'Delete', employee_path(employee.id), method: :delete %></td>

            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="p-3 mb-2 bg-dark text-light">
      <span class="text-info font-weight-bold">Welcome! </span>
      Register an employee
    </div>
  <% end %>
</div>

app/views/employees/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">New Employee</h4>
  </div>
  <div class="row justify-content-center">
    <%= form_with scope: :employee, url: employees_path, local: true do |form| %>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_area :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :position %>
        <%= form.text_field :position, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :employee_num %>
        <%= form.text_field :employee_num, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :employee_private_num %>
        <%= form.text_field :employee_private_num, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Show details of employee <%= @employee.name %></h4>
  </div>
  <div class="row justify-content-center">
    <table class="table">
      <tbody>
        <tr>
          <th>Email:</th>
          <td><%= @employee.email %></td>
        </tr>
        <tr>
          <th>Name:</th>
          <td><%= @employee.name %></td>
        </tr>
        <tr>
          <th>position:</th>
          <td><%= @employee.position %></td>
        </tr>
        <tr>
          <th>Employee Number:</th>
          <td><%= @employee.employee_num %></td>
        </tr>
        <tr>
          <th>Employee Private Number:</th>
          <td><%= @employee.employee_private_num %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/front_view/index.html.erb
<div>


  <div id="title"> <h1>Check-in/out</h1> </div>

  <div id='digital-clock'>
    <span id='hour'></span>
    <span class='dot'> :</span>
    <span id='min'></span>
    <span class='dot'>:</span>
    <span id='second'></span>
  </div>

  <p><div id="current_date"> </div></p>
  <script>
    date = new Date();
    year = date.getFullYear();
    month = date.getMonth() + 1;
    day = date.getDate();
    document.getElementById("current_date").innerHTML = day + "/" + month + "/" + year;
  </script>


  <div class="row justify-content-center text-center ">
    <%= form_with url: front_view_index_path, method: :post do |form| %>
        <div class="mb-2 ">
          <div>
            <%= form.label :"employee number:" %>
          </div>
          <%= form.number_field :employee_num %>
        </div>

        <div class="mb-2 pt-1">
          <div>
            <%= form.label :"private number:" %>
          </div>
          <%= form.password_field :employee_private_num %>
        </div>

        <div class="message">
          <% flash.each do |key, value| %>
            <div class="message__content <%= key %>">
              <%= value %>
            </div>
          <% end %>
        </div>

        <div class="check__buttons_container pt-1">
          <%= form.submit "Check in", name:"check", value:"in", class: "check__buttons_container__in " %>
          <%= form.submit "Check off", name:"check", value:"off",  class: "check__buttons_container__off " %>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BCDIC22RorRelojChecadorTeam3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link rel="stylesheet"   href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body style="background-color: #d4d8d5;">

    <% if current_page?('/users/sign_in') %> 
      <header class="checkin_header">
      <nav><%= link_to image_tag("FooCorp.png", alt: "Foo Corp", class: 'img-fluid'), front_view_index_path %>    
      </nav>
      </header>
    <%else%>

      <header class="checkin_header">
      <nav><%= link_to image_tag("FooCorp.png", alt: "Foo Corp", class: 'img-fluid'), front_view_index_path %>  
      <% if user_signed_in? %>
        <div class="d-md-flex justify-content-between align-items-center">
          <%= link_to "Return", :back %>
          <%= link_to "Admin menu", admin_admin_menu_path %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
        </div>
      <% else %>
        <%= button_to "Sign in", new_user_session_path, method: :get %> 
      <% end %>   
      </nav> 
      </header>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/reports/generate_report.html.erb
<div id="title"> <h1> Reports </h1> </div>

<div>
    <div class="graphs mb-5 mt-5">
        <h3>Attendance by day:</h3>
        <%= line_chart FrontView.group(:check).group_by_day(:created_at).count %>
    </div>

    <div class="graphs  mb-5">
        <div class="graphs_bar mb-5">
            <h3>checkin :</h3>
            <%= bar_chart FrontView.where(check: 'in').group_by_month(:created_at, format: "%Y-%B").count %>
        </div>
        <div class="graphs_bar">
            <h3>check off:</h3>
            <%= bar_chart FrontView.where(check: 'off').group_by_month(:created_at, format: "%Y-%B").count %>
        </div>
    </div>

    <div class="m-5 mb-5 text-center">
        <h3>Absences</h3>
        <table class="table table-bordered table-dark table-hover">
        <tr class="">
            <th>ID</th>
            <th>NAME</th>
            <th>DAYS WITH CHECK</th>
            <th>DAYS WITHOUT CHECK</th>
        </tr>
        <% @employees.each do |employee|  %>
        <% result = (employee.front_views.group_by_day(:created_at, range: employee.front_views.maximum(:created_at)..Time.now).count)%>
        <% daysYes = result.select { |k, v| v==1 }.keys %>
        <% daysNo = result.select { |k, v| v==0 }.keys %>
        <tr>
            <td><%= employee.id %></td>
            <td><%= employee.name %></td>
            <td>
            <% daysYes.each do |d| %>
            <%= simple_format "#{d.strftime('%B / %d / %Y ')} \n" %>
            <% end %>
            </td>
            <td>
            <% daysNo.each do |d| %>
            <%= simple_format "#{d.strftime('%B / %d / %Y ')} \n" %>
            <% end %>
            </td>
            </tr>
        <% end %>
        </table>
    </div>
</div>

app/views/reports/index.html.erb
<div id="title"> <h1> Reports </h1> </div>

<div  class="row justify-content-center">
    <div class="btn-lg pt-5 mt-5">
        <%= button_to "Generate report", reports_generate_report_path, method: :get %> 
    </div>
</div>

app/views/stores/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Edit Store</h4>
  </div>
  <div class="row justify-content-center">
    <%= form_with(model: @store, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_area :address, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/stores/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 display-4">Listing Stores</h4>
  </div>
  <%= link_to 'Register Store', new_store_path %>
  <% if @stores.present? %>
    <div class="row justify-content-center">
      <table class="table table-bordered table-dark">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col" colspan="3">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @stores.each do |store| %>
            <tr>
              <td><%= store.name %></td>
              <td><%= store.address %></td>
              <td><%= link_to 'Show', store_path(store.id) %></td>
              <td><%= link_to 'Edit', edit_store_path(store.id) %></td>   
              <td><%= button_to 'Delete', store_path(store.id), method: :delete %></td>           
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="p-3 mb-2 bg-dark text-light">
      <span class="text-info font-weight-bold">Welcome! </span>
      Register a Store
    </div>
  <% end %>
</div>

app/views/stores/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">New Store</h4>
  </div>
  <div class="row justify-content-center">
    <%= form_with scope: :store, url: stores_path, local: true do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_area :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/stores/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Show details of store <%= @store.name %></h4>
  </div>
  <div class="row justify-content-center">
    <table class="table">
      <tbody>
        <tr>
          <th>Name:</th>
          <td><%= @store.name %></td>
        </tr>
        <tr>
          <th>Address:</th>
          <td><%= @store.address %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>